### ISSUE TITLE
No connected sign on dungeonmastersvault

### ISSUE THREAD

**Issue by Slavanich** [averycrespi/vtt-bridge#106]
**Checklist**
- [X ] The [FAQ](https://github.com/averycrespi/vtt-bridge#faq) does not resolve my issue.
- [X ] This bug report is not [a duplicate](https://github.com/averycrespi/vtt-bridge/issues).

**Describe the bug**

**To Reproduce**
1. Go to 'Dungeonmastersvault.com'
2. Click on 'Character builder'
3. No connected to vtt bridge sign

**Expected behavior**
Connected to vtt bridge

**Screenshots**

![image](https://user-images.githubusercontent.com/73903511/98710137-142cfa00-23a5-11eb-822f-dad9ed2ec1f1.png)
![image](https://user-images.githubusercontent.com/73903511/98710162-1bec9e80-23a5-11eb-9b20-d1de1da5413f.png)

**Environment**
Please complete the following information:
- Device: *[e.g. iPhone, Desktop]*
- OS: *[e.g. Windows 10, Linux]*
- Browser: *[e.g. Google Chrome, Mozilla Firefox]*
- Extension version: *[e.g. v1.0.0]*
Google Chrome 1.4.0
**Additional context**
I have updated the extension but for some reason there still no connected to vtt bridge on dungeonmastersvault

**Comment by Slavanich** [comment]
Sorry about that i have been using wrong

**Comment by averycrespi** [comment]
I'm glad your issue was resolved!

I assume this was the problem?

> Make sure that you clicked the www link. If you are on the correct page, the URL should end with ?frame.
