### ISSUE TITLE
Chrome extension not stopping after close

### ISSUE THREAD

**Issue by Bixel925** [averycrespi/vtt-bridge#31]
The extension does not properly stop/close after closing/ending process of Chrome and Chrome based browsers. Tested in Vivaldi. After closing out the program reopening Vivaldi creates a [pop-up.](https://forum.vivaldi.net/assets/uploads/files/1530820855128-unbenannt.png) Removed folder containing extension and pop-up did not reappear.

**Comment by averycrespi** [comment]
I can't reproduce this in Chrome or Chromium.

Does the issue persist if you turn off "Continue running background apps when Google Chrome is closed" in chrome://settings/system (or the Vivaldi equivalent)?

**Comment by Bixel925** [comment]
Issue seems to have been caused by disabling background apps. Re-enabling background apps clears issue.

**Comment by averycrespi** [comment]
Excellent!
