### ISSUE TITLE
A way to have the roll go to everyone (default) or to just the DM/Game master

### ISSUE THREAD

**Issue by datdamnzotz** [averycrespi/vtt-bridge#37]
**Is your feature request related to a problem? Please describe.**
Perhaps a shift+d-click whispers to the GM/DM? (or some other key sequence)

as in:
`/me strikes a valiant pose.
Evil doer, beware, I am on your trail!
/w gm This is the signal that the thugs I paid are waiting for.`

**Comment by averycrespi** [comment]
Perhaps `Alt-Click`, so it can easily stack with advantage/disadvantage?

This should be relatively simple to implement.

**Comment by datdamnzotz** [comment]
That works! Whatever combo you want to implement  ; ]

**Comment by averycrespi** [comment]
This issue is being tracked in the `37-gm-roll` branch and is scheduled for the `v0.7.0` milestone.

**Comment by datdamnzotz** [comment]
Mac's don't have a Alt key, so you might want to do ctrlKey (windows) or metaKey (mac) click
Something like

`If (ctrlKey e) || (metaKey e) /w to dm`

**Comment by averycrespi** [comment]
Maybe a global toggle is more appropriate for this setting? e.g.

`Message visibility: Everyone (o---) Only me and the GM`

**Comment by datdamnzotz** [comment]
Long as it is easy to fip on and off.  : ]

**Comment by averycrespi** [comment]
Moving this to the next release, since I'll need to implement more complex state handling

**Comment by averycrespi** [comment]
This issue is being tracked on the `gm-roll` branch. I decided to toggle "Hidden Mode" when the H key is held down for 1 second.
