### ISSUE TITLE
Allow VTT to work with personal DMV servers

### ISSUE THREAD

**Issue by ashf** [averycrespi/vtt-bridge#38]
Currently VTT Bridge only works with dungeonmastersvault.com

I'd like it to work with any url that has a DMV instance running on it (for instance my personal server).

**Comment by ashf** [comment]
Could be something like this?

https://github.com/averycrespi/vtt-bridge/blob/master/manifest.json#L14

change to: "*://*/pages/dnd/5e/characters/*?frame=true"

**Comment by averycrespi** [comment]
This is possible, but I'd rather not give the extension such powerful permissions. 

It may be possible for the user to request additional permissions at runtime (via the [permissions API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions).

**Comment by averycrespi** [comment]
This issue is being tracked in the `38-optional-permissions` branch and is scheduled for the `v0.7.0` release.

**Comment by averycrespi** [comment]
Alright, I think this will work:

- Add a [toolbar button](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_action) for the extension
- In the toolbar page, add <kbd>Request</kbd> and <kbd>Revoke</kbd> buttons that use the [permissions API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) to enable the `*://*/pages/dnd/5e/characters/*?frame=true` origin.
- When permission is granted, use the [contentScripts API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts) to inject the appropriate DMV JS and CSS.

However, Chrome doesn't support the contentScripts API, so we may need to use a [polyfill](https://github.com/fregante/content-scripts-register-polyfill).
