### ISSUE TITLE
Link up the HP of a token in Roll20

### ISSUE THREAD

**Issue by matthias-D** [averycrespi/vtt-bridge#42]
**Is your feature request related to a problem? Please describe.**
When testing different tools I started with just Roll20, then went to dndbeyond for my charactersheets. Now I arrived at roll20 & DMV for my character sheets.

With the Beyond20 extension almost everything was linked to the 'empty' character sheet in Roll20, when I changed my HP on dndBeyond It also changed on my token on roll20.

Is there a way for VTTbridge to also implement this?

**Comment by averycrespi** [comment]
The code for how Beyond20 integrates with Roll20 is here: https://github.com/kakaroto/Beyond20/tree/master/src/roll20

I'll take a look at this, but there are higher priority issues to handle first.

**Comment by averycrespi** [comment]
This is a bit out-of-scope for VTT Bridge, since we only have unidirectional message from DMV to Roll20. 2-way synchronization would make the extension much more brittle, and I'd prefer to keep things simple.
