### ISSUE TITLE
roll damage for spells?

### ISSUE THREAD

**Issue by matthias-D** [averycrespi/vtt-bridge#43]
**Is your feature request related to a problem? Please describe.**
Spells only roll to attack but they do not roll damage after that?

**Describe the solution you'd like**
Roll damage as well, on a not hit we can ignore the damage

**Additional context**
Could be that I have completely missed this...

**Comment by averycrespi** [comment]
I had to rewrite most of the spell code to handle native buttons in v0.6.0, so some parts are still a WIP.

- Attack rolls: will be re-implemented soon
- Spell damage: This is really tricky. There's no distinct field for spell damage on DMV, so I would have to somehow extract it from the spell description. For now, this doesn't seem possible.

**Comment by averycrespi** [comment]
I've added support for the native Cast Spell description. They will print the spell name, casting level, and spell description. For now, that's the best I can do.

![Screenshot_20200511_163124](https://user-images.githubusercontent.com/9702999/81622119-fefaf280-93a4-11ea-8aad-bc6226266607.png)

This change will be available in v0.8.0
