### ISSUE TITLE
Mention Character Name in Roll

### ISSUE THREAD

**Issue by Sayyadina** [averycrespi/vtt-bridge#65]
**Describe the solution you'd like**
As a DM I'm running an NPC that has a DMV character sheet. If I roll on the sheet it says in Roll20 chat:

Ian (DM) (GM) rolls CHA save

12:57PM
Ian (DM) (GM): rolling 1d20+3

If possible it would be really handy for the bridge to pull the character's name from the sheet instead of "GM". That way if the NPCs fight each other we can keep the rolls straight.

Thanks again for this cool utility :)

- Drain

**Comment by averycrespi** [comment]
Yeah, that's possible! I'm a bit busy at the moment, but I'll add this to the backlog

**Comment by averycrespi** [comment]
Scheduled for release in v0.11.0
