### ISSUE TITLE
items that boost ASI in DMV don't translate over to Roll20 rolls.

### ISSUE THREAD

**Issue by Linkmysterious** [averycrespi/vtt-bridge#80]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by averycrespi** [comment]
I can't seem to reproduce this. After equipping the Gauntlets of Ogre Power, VTT Bridge appears to generate the correct commands: `Ran commands: ["/em : Player rolls STR check","/roll 1d20+4"]`.

Can you provide more information?

**Comment by Linkmysterious** [comment]
Upon trying it again it.. seems to work fine. So I have no clue.

My theory was originally maybe it only works with custom items. But it seems to be working fine. I'm honestly not sure. It was definitely acting as a +4 instead of a +5 earlier, so I don't know what caused that and subsequently fixed it. I'm gonna mark this as closed because like i said earlier it seems to be working now. I'll update if it happens again, and give more documentation.

**Comment by averycrespi** [comment]
Let me know if it happens again!

Possible cause: if DMV updates the ability scores *after* VTT Bridge creates its event listeners, a bug like this could occur.
